### ISSUE TITLE
Problem with events

### ISSUE THREAD

**Issue by vomchik** [jpillora/xdomain#101]
Hi. Event property target always null. I expected link to instance of XMLHttpRequest.

I use [**weinre**](http://people.apache.org/~pmuellr/weinre/docs/latest/Home.html) tool for remote debugging my mobile app. 

And theirs js script contains next code:

``` javascript
        _xhrEventHandler = function(event) {
            var xhr;
            xhr = event.target;
            if (xhr.readyState !== 4) {
                return;
            }
            return xhr.httpSocketHandler.call(xhr.httpSocket, xhr);
        };
```

**Comment by jpillora** [comment]
XHook's [clone event code](https://github.com/jpillora/xhook/blob/gh-pages/src/xhook.coffee#L37-L38) should do this, though it seems there's a bug

**Comment by jpillora** [comment]
Looking into this, so there was a previous bug where people needed an instance of an `Event` instead of an object with all the properties copied. That was fixed, though this now means that `target` is readonly. Which now breaks this functionality.

Can weinre be hacked to not use event.target? Chromes mobile emulation is quite good, have you looked into that?

**Comment by jpillora** [comment]
closing as wont fix since it seems the only way is to revert to non-`Event` objects
