### ISSUE TITLE
Deprecated CDN URL

### ISSUE THREAD

**Issue by cdamley** [jpillora/xdomain#133]
I am downloading xdomain from this CDN - "http://cdn.rawgit.com/jpillora/xdomain/gh-pages/dist/0.6/xdomain.min.js"

I occasionally see this warning in my console - "XDomain: The URL to this script will soon be deprecated - please see https://github.com/jpillora/xdomain#download".

Just want to know how long will this deprecated URL be available?

**Comment by jpillora** [comment]
Those URLs used to link straight into the `gh-pages` branch. I've since moved to using tagged releases. So basically http://cdn.rawgit.com/jpillora/xdomain/0.6.17/dist/xdomain.min.js won't change since it refers to `0.6.17`. I'd like to completely remove all versions from the repo (the `0.6` from `dist/0.6/xdomain.min.js`), though I can imagine people are still using this link. I won't change it any time soon (maybe another 12 months), though still, it's safest to move to the new tagged distribution links.
