### ISSUE TITLE
BUG: Xdomain attempting (and failing) to handle other crossdomain requests on the same page

### ISSUE THREAD

**Issue by ejbaker** [jpillora/xdomain#141]
In production, the page where I'm using xdomain also makes other requests I can't control. (ad units) With debug mode set, I get the following messages:

xdomain (http://stage.www.example.com): adding slave: http://subdomain.example.com:3000
xdomain (http://stage.www.example.com): no slave matching: 'http://diffsubdomain.diffdomain.com'

and at this point, the script shuts down.

Is there any way to constrain xdomain so that it will _only_ attempt to proxy requests directed at its slave?

**Comment by jpillora** [comment]
When `no slave matching` appears, it should skip XDomain. In order to hook ajax requests, XHook must replace the entire `XMLHttpRequest` object. I can't say where things are going wrong based on those logs, can you make a live demo reproducing this?  (Please use unminified versions of all included scripts)

As a hacky work around in the meantime, you could initially `xhook.disable()`, then for every request:

``` js
xhook.enable();
$.ajax(...);
xhook.disable();
```

**Comment by alpeshgaglani** [comment]
I have the same issue. For my case, I'm using angularjs to upload a file to a different domain. This domain is different from the master, as well as any of the slaves. It looks like angularjs adds a method called "__setXHR_" to the request.headers. The way xhook tries to do the send is by looping through all the request headers using for .. in loop, thereby trying to set a header called __setXHR_ with value being the stringified function. On IE10, this crashes with a DOMException.
