### ISSUE TITLE
Document when a CORS polyfill is required.

### ISSUE THREAD

**Issue by lovelydinosaur** [jpillora/xdomain#17]
It's not obvious if and when a CORS polyfill is required.  It might be good to note which browsers do not support CORS and make it more clear if and how this polyfill differs from the behaviour that a standard "Access-Control-Allow-Origin: *" header allows.

**Comment by odino** [comment]
IE8/9, nuff said :)

**Comment by jpillora** [comment]
Hi Tom, just curious, how'd you find this repo if you weren't already looking for a polyfill?

As @odino says, it's mainly for IE8/9, however it can also be used to normalize XHR. Since the [CORS spec](http://www.w3.org/TR/cors/) isn't just "add headers. done.", there's actually more to it. IE8/9 do have CORS, though it uses a different API to normal browsers. So XDomain can be seen as a **simpler** alternative, as it _it's just normal XHR_. Also you can read https://github.com/jpillora/xdomain#faq.

You're free to PR an explaination by [editing the README.md](https://github.com/jpillora/xdomain/edit/gh-pages/README.md) if you like :)

**Comment by lovelydinosaur** [comment]
I just found it non-obvious taking a look at the README when I would or wouldn't need to use this instead of CORS.
The FAQ is probably sufficient, but I guess you might consider expanding the summary very slightly to address _when_ and _why_ this is a useful alternative.

> how'd you find this repo if you weren't already looking for a polyfill?

The internets have their ways. :sparkles: :space_invader:

**Comment by jpillora** [comment]
Slightly updated the [FAQ](https://github.com/jpillora/xdomain#faq) :)
