### ISSUE TITLE
xdomain incompatibility with latest build of angular

### ISSUE THREAD

**Issue by odino** [jpillora/xdomain#32]
Hey @jpillora, we have seen a strange case where GET request would return an empty body when using xdomai with the latest angular build from bower, as it seems that thy conflict in the way the response is set (xhr.response / xhr.responseText).

If you have a look the guys at angular actually did a change a file called httpBackend.js that works with the response body...

We're looking into it but I thought its worth mentioning...

**Comment by jpillora** [comment]
Thanks for the heads up, will take a look when I can, I've been on back end
stuff for a while now - need to find some spare time!

**Comment by odino** [comment]
it actually just might be our minificator, will keep you guys updated

**Comment by mattlanham** [comment]
I opened an angular issue on this, and later found this :) 

From version 1.2.8 of Angular, they replaced a line in the XHR handler that now reads this:

response = ('response' in xhr) ? xhr.response : xhr.responseText;

Before this change ( < 1.2.7), it was:

response = xhr.responseType ? xhr.response : xhr.responseText;

Changing it back resolves the issue, but it seems to be a bug in xdomain that is causing the response to be returned as null, and then the above check evaluates to true and uses the null response, instead of the responseText.

It's worth noting that this seems to only happen for me when the API i'm connecting to uses SSL, if i connect to the same API without SSL it seems response is not null.

Hope this helps resolve the issue.

**Comment by odino** [comment]
FYI this has been fixed [on xhook](https://github.com/jpillora/xhook/commit/37376e25011273a7442d3cd279c801ee1a62919e#diff-819ae63166668c39ba0cf743ae514eeaR213)

**Comment by jpillora** [comment]
https://github.com/jpillora/xdomain/pull/33#issuecomment-32679394

> Hey guys, this fix is in xhook, though the xdomain merge is still in progress as new features are going in at the same time, sorry about the delay

**Comment by odino** [comment]
cant we cherry pick it the single change in xdomain?

**Comment by jpillora** [comment]
Was hoping `v0.6.x` would be ready soon, though it's looking more complex than I planned. So, just cherry pick it now.
