### ISSUE TITLE
Better scoping of events.

### ISSUE THREAD

**Issue by tristanz** [jpillora/xdomain#35]
I have an application that uses postMessage directly.  This causes errors with the xdomain Ajax requests.  In particular, I'm sending objects rather than strings, so the JSON.parse throws.

**Comment by jpillora** [comment]
Ah yes, this is an issue indeed. The problem is kind of a limitation with the postMessage API, with it being a single event emitter. In the next release, I'll silently throw away the errors, which I think is the only solution. Though I'm open to suggestions. Edit: A thought - I'll prepend `XDOMAIN_` to the event message string and throw it away if it doesn't contain this string.

**Comment by tristanz** [comment]
The XDOMAIN_ was what I was thinking.  And checking that it is a string to begin with, since more recent browsers support objects directly.

**Comment by jpillora** [comment]
Fixed, I'm now ignoring anything that's not an array object, with an xdomain ID as the first value
