### ISSUE TITLE
add the server side version to npm?

### ISSUE THREAD

**Issue by saintmac** [jpillora/xdomain#43]
the package would just contain the latest version of /dist/x.y/xdomain.min.js

**Comment by jpillora** [comment]
There isn't really a server side version, all distributions contain both master and slave portions of the code. Since the server-side setup is really just placing the `proxy.html` file along with your static files, I don't see how it would be suited for npm? However, maybe a express middleware to respond to `/proxy.html` with the latest xdomain? This wouldn't save the user much trouble though...

**Comment by LongLiveCHIEF** [comment]
I was thinking about his same thing before I found your library.  The one thing node can really help with is a live i/o connection between the two endpoints, as opposed to a request response.  this wouldn't be xhr really, but to the app with the `master`, you could still use it as if it was.

That's my take anyways.

**Comment by jpillora** [comment]
Not sure how you could use XDomain in particular to create a websockets-like connect? I think I'll close this. Will reopen if there's a technically sound use case.

**Comment by LongLiveCHIEF** [comment]
even if there's a way you can, it's not going to work with IE 8/9. And anything later has better CORS support (except for that first pre-patched version of IE10 that has problems with `Cookie` headers)

**Comment by jpillora** [comment]
Not sure how CORS relates to websockets... You can do long-polling, which would work IE8/9, but that's still unrelated to CORS... anyways

**Comment by LongLiveCHIEF** [comment]
The only argument that can be made is to use it as a pass-through proxy to proxy service that makes certain Authentication schemes (specifically I'm thinking of `NTLM`) feasible due to issues with xhr cross-origin authentication squashing.  

But as you indicated, the better solution is just to make xdomain perfect, and you are indeed nearly there.

**Comment by wyuenho** [comment]
@jpillora Can you reopen this issue? I'd really like to be able to npm install this for use with webpack. Thanks!
