### ISSUE TITLE
Add Api function to allow for config

### ISSUE THREAD

**Issue by LongLiveCHIEF** [jpillora/xdomain#50]
Based on [this api suggestion for xhook](https://github.com/jpillora/xhook/issues/12) and also #48 

Config method options:
- [ ] set 'withCredentials: true'
- [ ] default interference handling (on/off) default being true
- [ ] set default handling for `withCredentials` requests (#12)
- [ ] set an interference exceptions option to override the current interference setting
- [ ] implement and/or to prevent conflicting directives

Allow for: 

```
<script>
   xdomain.config({
        interfere:true, //this is the default setting,
        withCredentials, //represents the default, can be turned around here globally, or in configs below individually
        //options in this section will override the interfere setting (true by
        exceptions: { 
                  // array of objects, each representing a group of settings from the config list below
                 x_or: [  ], 
                 x_and: [  ]
          }
     });
 </script>
```
### Or/And config settings (maybe use `any`/`all` instead?)
- [ ] user-agent `string/array`
- [ ] content-type `string`
- [ ] destination host `string/array`
- [ ] methods `string/array`
- [ ] paths `string/array` (paths from origin that overide the current interfere setting)

**Comment by jpillora** [comment]
I hadn't implemented this feature yet because XDomain only interferes with requests destined for a slave domain and if you are explicitly defining slave domains then I'd imagine all requests to that domain would want to be hooked. If they weren't hooked then the browser would use CORS, and if you're using CORS then why add XDomain to mix anyway?

Nevertheless, if there is a sound use case. I'll add this feature. Although, instead of a series of complex configuration options, how about a filter function?

Defaults to:

``` js
xdomain.filter = function(req) {
  return true;
};
```

Where `req` is an [XHook Request Object](https://github.com/jpillora/xhook#request-object)

**Comment by LongLiveCHIEF** [comment]
Yeah, that could definitely work.  But I'm finding that your library is affecting my calls to non-slaved servers, and it's toxic to my system.  Adding the ability to control it a bit better would make it useable.

What's happening is that I basically have 4 subdomains (one represents my renaming of localhost), of a parent domain.  And while one of the servers out of 4 doesn't have CORS support, adding your library kills access to the others because it's not letting my credentials through.  (Basically, it's intercepting the requests just to determine to let them go through anyways... and in the process is unintentionally altering the request)

**Comment by jpillora** [comment]
> Basically, it's intercepting the requests just to determine to let them go through anyways... and in the process is unintentionally altering the request

Yup there's the crux of the problem. I did foresee this problem right from the beginning however the only way I could add all the hooking features I wanted (XHook) was to completely reimplement my own XMLHttpRequest. If my XMLHttpRequest isn't perfect, then just by including it can create issues (like no `sendCredentials` support), so basically, the only solution is to make my implement perfect - and it's getting there.

And the about `filter` feature, it would only dictate whether or not to send the request over to an iframe. The decision about whether to hook the request is part of XHook and it _must_ use the `interefere all` model, otherwise it won't work at all. **Only** when you do `new XMLHttpRequest()`,  can I decide whether to hook or not, and at that point I have no information about what you're doing with the request.

**Comment by LongLiveCHIEF** [comment]
That makes sense.  And it does give me an idea about how to support what I'm doing internally before one of us gets a chance to write in the auth filter.

I'm using Angular, so I need to double check on the timing of things, but if they're what I think they are, I can set a request interceptor to re-attach the credentials before they go through.

If xhook is grabbing it and returning it before the call is actually sent, then I think it will work.

**Comment by jpillora** [comment]
So I've had a think, the best thing I can do is `xhook.enable()` and `xhook.disable()`. Will close this issue and make it a new feature on XHook issues

**Comment by LongLiveCHIEF** [comment]
:+1:
