### ISSUE TITLE
XDomain's XHR used for non-CORS calls, XDomain/XHook support for async: true

### ISSUE THREAD

**Issue by jonahsimpson** [jpillora/xdomain#60]
First, let me say I love this plugin!

However...I implemented XDomain on my current project and immediately ran into issues because in some places we use async: false on our jQuery AJAX calls, which is not currently supported by XHook. Admittedly, this is a bad architecture on our part, but it shed some light that XHook is being used on every XHR request and doesn't get selectively implemented for just the CORS requests that I expected XDomain to be wrapping. 

While we can definitely fix the async: false issues, this issue did give me a bit of a concern about the scope of the changes to the XHR object. I'm probably being naive, I just wish I could slot this plugin in to give me universal, consistent CORS access without affecting non-CORS requests in any way. 

I don't necessarily expect any fixes to come directly from this issue, just wanted to raise it more for (idealistic!) awareness. In the meantime, I'll be more selective about including the library and fix all my stupid async: false calls. 

Thanks again for all your hard work!

**Comment by jpillora** [comment]
Since XHook allows for async hooks, an XMLHttpRequest could be set to sync, though still execute asynchronously due to a given async hook. XDomain creates one such hook to create a seamless CORS replacement. In some cases, like yours, I could go ahead and allow the sync request, which would most likely fix your issue. In other cases however, instead of throwing an error message, it would create silent, difficult to find async bug. I'm also morally opposed to sync XHR :P

One work around could be to `xhook.disable()`, then run your sync request then `xhook.enable()` right after.

And re: scope of changes to XMLHttpRequest. I'm attempting to perfectly implement XMLHttpRequest2 in XHook. The `sync` feature is probably the only thing missing from XHook (that I know of). And then when XDomain uses XHook, due to cross-domain restrictions, the `withCredentials` feature sends the master cookies using the `XDomain-Cookies` header instead of the `Cookies` header.

**Comment by jonahsimpson** [comment]
I understand your reservations about async XHR, however, can you comment about why you chose to use XHookeven for non-CORS requests? I guess I was thinking that non-CORS requests would end up calling the native XHR object, rather than the XHR object that's been wrapped with XHook...

Thanks again!

**Comment by jpillora** [comment]
From the beginning, that was my intent, however in order to read the URL to
determine if its CORS or not, the request must be hooked. So that's why
it's always on. I could provide the manual overrides, though that's about
all I could do

**Comment by robertocr** [comment]
I have just faced this problem!
This happened because I inject dynamically loaded html (with its own dependencies inside), so it's wise to use async : false
I just had to find the sync ajax request in my code, disable xhook on beforeSend and enable xhook on complete, as suggested. (see http://api.jquery.com/Ajax_Events/ if you're using jquery)
Thank you all very much for sharing :smiley: :+1:

ps: this could be more explicitly listed as a potential pitfall... I think I was just lucky to notice this really quick, because this feels like the kind of thing people can take hours to know what's up (if they ever remember xdomain.min.js is up, it's a pretty silent problem)

**Comment by jpillora** [comment]
Hey guys just an update to this, I've implemented sync requests in XHook to fix [a chrome iOS bug](https://github.com/jpillora/xhook/issues/23#issuecomment-53958934) so this should resolve some of these issues. Though note, when the request is sync, **async hooks must be skipped** and this includes XDomain so this just attempts to allow external code to operate correctly, we still can't use XDomain with sync calls.
