### ISSUE TITLE
Hidden iframe being removed by Angular

### ISSUE THREAD

**Issue by ghost** [jpillora/xdomain#80]
I am using this plugin in AngularJS and is having problems in Chrome when navigating from one page to another, is basically loading the full html into the body including the head and scripts.

I am using ui-view of angularjs.

**Comment by jpillora** [comment]
That sounds like it will remove the iframe that xdomain creates. Can you do something like

``` html
<body>
<container ng-view>
</container>
</body>
```

?

**Comment by ghost** [comment]
I tried it and it worked but i'm using ui-router which uses ui-view and I want to use this

**Comment by jpillora** [comment]
I'm closing this because, although I could detect the missing iframe and recreate it, doing so over and over is inefficient and would slow down XHR a great deal. The better solution is to find a way to make your `<body>` replacing library, Angular or whichever, instead replace a `<conatiner>` as mentioned above.
