### ISSUE TITLE
Conflicts with existing postMessage logic

### ISSUE THREAD

**Issue by newtriks** [jpillora/xdomain#82]
Thanks for the library, seems a solid solution. I was wondering if you envisage conflicts within applications already implementing postMessage? A quick test in an Angular app that calls a rails api seems to create errors in the existing postMessage logic the apps relied on.

**Comment by jpillora** [comment]
Since post message has a terrible API, this can't be helped - you can
create many message listeners, but they will all fire on all messages.
XDomain protects itself by only accepting XDomain messages. Basically if
you have multiple windows posting you messages, you need to ensure they're
discernable. For example in example, I send arrays with something like:

[ "xdomain-ef13ds", { .. actual message }]

So if you can make your code also emit your own wrapper, then you your app
can throw away the messages that it doesn't care about

**Comment by newtriks** [comment]
@jpillora thanks and I agree about the postMessage API :+1:
